baseURL: ""
languageCode: en-us
title: zhanxin
theme: PaperMod

params:
  homeInfoParams:
    Title: "思考,阅读"
    Content: "Done is Better Than Perfect"

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 10
